apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barista
  namespace: qhftd-argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: qhftd-prod-coffeeshop
  project: coffee-shop
  source:
    path: ./coffee-shop-kustomize/barista/overlays/production
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/dneves-redhat.com-qhftd/coffee-shop-final-lab.git
    targetRevision: HEAD
