apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-pipeline
  namespace: qhftd-argocd
spec:
  destination:
    namespace: qhftd-pipeline
    server: https://kubernetes.default.svc
  project: coffee-shop
  source:
    path: ./coffee-shop-pipeline
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/dneves-redhat.com-qhftd/coffee-shop-final-lab.git
    targetRevision: HEAD
